import React from 'react'
import AboutUs from '../Components/AboutUs'

export const metadata = {
  title: "About Us | Ecommerce Website",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <AboutUs/>
    </>
  )
}
