import React from 'react'
import ProductListings from '../Components/ProductListing';

export const metadata = {
  title: "Products | Ecommerce Website",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
      <ProductListings/>
    </>
  )
}
