"use client"
import { useRouter } from 'next/navigation';
import React from 'react'

// export const metadata = {
//   title: "About Us",
//   description: "Generated by create next app",
// };

export default function page() {

  const router = useRouter();

  router.push('/')

  return (
    <>
      About Us
    </>
  )
}
