import '../assets/css/style.css'
import MainLayout from './Components/Common/MainLayout';

export const metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
