import { productAPI } from "./ApiServices/HomeAPI";
import Home from "./Components/Home";

export const metadata = {
  title: "Home Page | Ecommerce Website",
  description: "Generated by create next app",
};

export default async function page() {

  const products = await productAPI();

  return (
    <>
      <Home products={products}/>
    </>
  );
}
