import Link from "next/link";
import "./assets/css/style.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <div>
      <Link href={`/`}> Home </Link>
    </div>
    <div>
      <Link href={`category`}> Category </Link>
    </div>
    <div>
        <Link href={`about-us`}> About Us </Link>
    </div>

        {children}
      </body>
    </html>
  );
}