import Image from "next/image";
import Home from "./Components/Home";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function page() {

  return (
    <>
      <Home/>
    </>
  );
}
