import '../../assets/css/style.css'

export const metadata = {
  title: "Admin Panel | Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
